[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "function Card:update(dt)"
position = "after"
payload = """
    if G.STAGE == G.STAGES.RUN and self.config.center.key == 'j_666_multiplying' then
        local other_joker = nil
        for i = 1, #G.jokers.cards do if G.jokers.cards[i] == self then other_joker = G.jokers.cards[i+1] end end
        if other_joker and other_joker ~= self and other_joker.config.center.blueprint_compat then
            self.ability.blueprint_compat = 'compatible'
            self.ability.blueprint_compat_ui = localize('k_compatible')
            self.ability.blueprint_compat_check = true
        else
            self.ability.blueprint_compat = 'incompatible'
            self.ability.blueprint_compat_ui = localize('k_incompatible')
            self.ability.blueprint_compat_check = false
        end
    end"""
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Blueprint' then"
position = "before"
payload = """elseif self.config.center.key == 'j_666_multiplying' then
    self.ability.blueprint_compat_ui = self.ability.blueprint_compat_ui or ''; self.ability.blueprint_compat_check = nil
    main_end = (self.area and self.area == G.jokers) and {
        {n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={
            {n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.JOKER_GREY, r = 0.05, padding = 0.06, func = 'blueprint_compat'}, nodes={
                {n=G.UIT.T, config={ref_table = self.ability, ref_value = 'blueprint_compat_ui',colour = G.C.UI.TEXT_LIGHT, scale = 0.32*0.8}},
            }}
        }}
    } or nil"""
match_indent = true
